sudo: required
# have to use a different language otherwise
# the minimalistic image is used and postgres
# and docker are missing
language: go
services:
- postgresql
- docker
- redis
matrix:
  include:
  - env: PROJECT=diaspora
  - env: PROJECT=ganggo
  - env: PROJECT=mastodon
  - env: PROJECT=socialhome
install: bash scripts/install.sh
script: bats --tap $(find . -name $PROJECT'*.bats')
