sudo: required
# have to use a different language otherwise
# the minimalistic image is used and postgres
# and docker are missing
language: go
services:
- postgresql
- docker
install:
- |
  sudo curl -o /usr/local/bin/jq -L \
    https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
  git clone --depth 1 https://github.com/sstephenson/bats.git
  cd bats && sudo ./install.sh /usr/local
script:
- cd $TRAVIS_BUILD_DIR && bats --tap .
