sudo: required
# have to use a different language otherwise
# the minimalistic image is used and postgres
# and docker are missing
language: go
services:
- postgresql
- docker
install:
- git clone --depth 1 https://github.com/sstephenson/bats.git
- cd bats && sudo ./install.sh /usr/local
script:
- cd $TRAVIS_BUILD_DIR && bats --tap .
